// Generated by CoffeeScript 1.7.1

/**
 * Copyright © 2014 mparaiso <mparaiso@online.fr>. All Rights Reserved.
 * Snipped , manage your snippets online
 */

(function() {
  module.exports = function(c) {

    /*
         EVENT HANDLERS
     */
    return c.set('events', c.share(function(c) {
      var events;
      events = {
        'SNIPPET_EDIT': 'SNIPPET_EDIT',
        'SNIPPET_BEFORE_UPDATE': 'SNIPPET_BEFORE_UPDATE',
        'SNIPPET_AFTER_UPDATE': 'SNIPPET_AFTER_UPDATE'
      };

      /* testing a few events */
      c.qevent.on(events.SNIPPET_BEFORE_UPDATE, function(snippet, req, res) {
        return console.log('snippet before update %s with id %s', snippet, snippet.id);
      });
      c.qevent.on(events.SNIPPET_AFTER_UPDATE, function(snippet) {
        return console.log('snippet after update %s with id %s', snippet, snippet.id);
      });
      return events;
    }));
  };

}).call(this);
