<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Snippet
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Snippet extends EntityRepository
{
}
