##
#
# USER
#
##


admin_user_create:
    pattern: /admin/user/create.{format}
    defaults: { _controller: Controller\UserController::create, format: "html" }
   
admin_user_update:
    pattern: /admin/user/update/{id}.{format}
    defaults: { _controller: Controller\UserController::create, format: "html" }
    
admin_user_read:
    pattern: /admin/user/read/{id}.{format}
    defaults: { _controller: Controller\UserController::create, format: "html" }
    requirements:
        id: \d+
        format: \w+
        
admin_user_delete:
    pattern: /admin/user/delete/{id}.{format}
    defaults: { _controller: Controller\UserController::delete, format: "html" }
    requirements:
        method: POST
        id: \d+
        format: \w+
        
admin_user_index:
    pattern: /admin/user/{format}
    defaults: { _controller: Controller\UserController::index, format: "html" }
    requirements:
        format: \w+
    
##
#
# SNIPPETS
#
##
snippet_index:
    pattern: /snippet
    defaults: { _controller: Controller\SnippetController::index, format: "html" }
    
snippet_read_by_id:
    pattern: /snippet/{id}.{format}
    defaults: { _controller: Controller\SnippetController::read, format: "html" }
    requirements:
        id: \d+

snippet_create:
    pattern: /private/snippet/create.{format}
    defaults: { _controller: Controller\SnippetController::create, format: "html" }

snippet_update:
    pattern: /private/snippet/update/{id}.{format}
    defaults: { _controller: Controller\SnippetController::update, format: "html" }
    
snippet_delete:
    pattern: /private/snippet/delete/{id}.{format}
    defaults: { _controller: Controller\SnippetController::delete, format: "html" }
    requirements:
        method: POST
    
##
#
# CATEGORIES
#
##    
 
category_read:
    pattern: /private/category/read/{id}.{format}
    defaults: {_controller: Controller\CategoryController::read, format: "html"}
    requirements:
      format: \w+

category_create:
    pattern: /private/category/create.{format}
    defaults: {_controller: Controller\CategoryController::create ,format: "html" }
    requirements:
      format: \w+
      
# DEFAULT      
       
index:
    pattern: /{format}
    defaults: { _controller: "Controller\DefaultController::index" , format: "html" }
    